name: Deploy To Staging (Clients)
on:
  push:
    branches:
      - staging

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: 🎉 Deploy
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.4
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build

      - name: 🚀 Uploading To INC1 Clients
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: "34.246.236.253"
          port: 22
          username: "webftp"
          password: "Increas!ngly!@!#"
          localPath: "build"
          remotePath: "/var/www/html/Clients/flUN19e/"

      - name: 🚀 Uploading To INC2 Clients
        id: upload2
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: "99.80.203.129"
          port: 22
          username: "webftp"
          password: "Increas!ngly!@!#"
          localPath: "build"
          remotePath: "/var/www/html/Clients/flUN19e/"

      - name: 🚀 Uploading To UK3 Clients
        id: upload3
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: "79.125.127.153"
          port: 22
          username: "webftp"
          password: "Increas!ngly!@!#"
          localPath: "build"
          remotePath: "/var/www/html/Clients/flUN19e/"
